### ISSUE TITLE
Typescript error: Could not find a declaration file for module react-ray.

### ISSUE THREAD

**Issue by danito72** [permafrost-dev/react-ray#76]
I am using react-ray in a Laravel Inertia with a React typescript setup, running on Wsl2 with laravel sail.

On import this error happens:

TS7016: Could not find a declaration file for module react-ray.
/home/danny/code/projects/bior/node_modules/react-ray/dist/index.esm.mjs
implicitly has an any type.
There are types at
/home/danny/code/projects/bior/node_modules/react-ray/dist/index.d.ts
, but this result could not be resolved when respecting package.json exports. The react-ray library may need to update its package.json or typings.

**Comment by patinthehat** [comment]
@danito72 Thank you for reporting this, I'll look into it and update accordingly.

**Comment by justrustyspoons** [comment]
I have the same issue. None of these next/react ray packages work.

**Comment by patinthehat** [comment]
@justrustyspoons You can use `node-ray` as a workaround. react-ray uses it internally anyway. Thank you for reporting the issue as well, I will look into it as time permits or I'd be happy to review a PR. Thanks again! 👍
